proxy:
  enable_remote_connection: false
  port: 3128
  output_proxy_uri: "" #http://localhost:3129
  add_windows_authentication_to_output_proxy: false # only for windows
  require_windows_authentication: false # only for windows
webui:
  port: 9000
  enable_remote_connection: false
